port: 9600
environment: production
address: 127.0.0.1
pid_file: /home/993440e2/web/matchbox/shared/pids/mongrel.pid
log_file: /home/993440e2/web/matchbox/shared/log/mongrel.log
servers: 1
docroot: /home/993440e2/web/matchbox/current/public
cwd: /home/993440e2/web/matchbox/current
