#! /bin/sh

PATH=/opt/local/bin:/opt/local/sbin:/usr/xpg4/bin:/usr/sbin:/usr/bin:/usr/sfw/bin:/usr/ccs/bin:/usr/openwin/bin

case "$1" in
  start)
	  echo 'Starting ultrasphinx'
	  sudo /opt/local/bin/rake  -f /home/993440e2/web/matchbox/current/Rakefile ultrasphinx:daemon:start RAILS_ENV=production
		;;

	restart)
	  echo 'Restarting ultrasphinx'
	  sudo /opt/local/bin/rake  -f /home/993440e2/web/matchbox/current/Rakefile ultrasphinx:daemon:restart RAILS_ENV=production
		;;
		
  stop)
	  echo 'Stopping ultrasphinx'
	  sudo /opt/local/bin/rake  -f /home/993440e2/web/matchbox/current/Rakefile ultrasphinx:daemon:stop RAILS_ENV=production
		;;

  reload|force-reload)
		echo "Error: argument '$1' not supported" >&2
		exit 3
		;;
		
  *)
	echo "Usage: $0 start|stop|restart" >&2
	exit 0
	;;
esac